### ISSUE TITLE
Down-/Upload speed is not saved.

### ISSUE THREAD

**Issue by sehraf** [RetroShare/RSNewWebUI#10]
Changing the values under config -> network does not result in anything. The values stay the same. (Also i don't see a corresponding api call to `rsConfig/SetMaxDataRates`)

**Comment by rottencandy** [comment]
It looks like mithril is converting the input value to a string, which the API does not accept. I can fix this. The request are being sent though.



The client also does not seem to update it's display when the Download/Upload values change.
For example, sending a request to change the speeds:
```sh
 curl -u test:test http://127.0.0.1:9092/rsConfig/SetMaxDataRates -d '{"downKb": 300, "upKb": 250}'
```
seems to update the values, which can be confirmed by:
```sh
 curl -u test:test http://127.0.0.1:9092/rsConfigGetMaxDataRates
```
But this change is not reflected in the client UI.
CC: @csoler
