### ISSUE TITLE
Port Number display at login is needed?

### ISSUE THREAD

**Issue by defnax** [RetroShare/RSNewWebUI#14]
Hi,
i dont know if the Port number is importend on login to display.
when you change the port in settings the default value changes.
the webui doesnt know that i use port 9090.
Normaly it needs to detect automacticly the port which is stored in the settings.

For me the port number display is for advanced users, its only enough in the settings to change/show.

On ZeroNet, I2P they doesnt requiere to give the Port number on login/start the web interface.

![image](https://user-images.githubusercontent.com/9952056/102724327-14f36d00-430f-11eb-9a2e-dba7c8ee6bc4.png)

![image](https://user-images.githubusercontent.com/9952056/102724306-ed9ca000-430e-11eb-8456-cf7a788bd79c.png)

**Comment by csoler** [comment]
For sure what you can hide is the login. .It's hard-coded to be webui and there's no reason to have a login anyway. It's only a passwd access since there's no specific profile for the webUI: your profile is given by the current node's profile.

**Comment by defnax** [comment]
> For sure what you can hide is the login. .It's hard-coded to be webui and there's no reason to have a login anyway. It's only a passwd access since there's no specific profile for the webUI: your profile is given by the current node's profile.

ok, maybe when the webui is going to be more ready then we can it hide it.

**Comment by zeners** [comment]
fixed in #14 with 3c7324b0
