### ISSUE TITLE
javascript not found

### ISSUE THREAD

**Issue by orien3243** [RetroShare/RSNewWebUI#15]
So I run it in chrome and firefox on ubuntu 20.04 and I open the index.html file and get a "no javascript found" but app.js is accessible. 

app.js:81 Uncaught Error: Cannot find module "main" from "/"
    at require (app.js:81)
    at load_ui ((index):19)
    at onload ((index):12)
    
I heard Zapek is working on this. Is there something you guys think I can help with?

**Comment by rottencandy** [comment]
Can you give some more info about your browser version?

**Comment by defnax** [comment]
normaly you must open from retroshare or with right link (when json api enabled and webui too from Retroshare settings)
http://127.0.0.1:9090/index.html

but open from folder will not work.
![image](https://user-images.githubusercontent.com/9952056/106387954-87f70580-63dc-11eb-9af7-e974921391b3.png)

**Comment by orien3243** [comment]
Well I did this in the latest chrome. 88.0.4324.104 (Official Build) (64-bit) (cohort: Stable)

I am using the retroshare app image (6.5-retroshare-gui-obs-APPIMAGE) and it does have an option for a JSON API but no option to "show web interface" to try out after building this github package. 

Thats why I tried to just click on the index.html file. Is this not the correct way to test this package out?

So what I am doing is using the windows retroshare package (6.5-1-gfb005f041), this version by default has the old web ui (the black terminal one with access to chat and so fourth)

**Comment by defnax** [comment]
i think the app image doesnt contains the webui when im right. You are on rs network right? use latest Windows package from  Nyvenza or build from master for  windows or linux with json api/webui enabled.
You want develope on webui right?

**Comment by orien3243** [comment]
okay and yes.

**Comment by defnax** [comment]
@rottencandy close tihs
