### ISSUE TITLE
Logic code is not defined in People>Edit identity for changing identity

### ISSUE THREAD

**Issue by Kumaravinash9** [RetroShare/RSNewWebUI#26]
# Edit Screen 
![edit](https://user-images.githubusercontent.com/64456168/112930475-fbe13000-9137-11eb-8e33-889034c61781.JPG)

**Comment by Kumaravinash9** [comment]
# Create new identity 

![identity](https://user-images.githubusercontent.com/64456168/112987559-7b92ed00-9180-11eb-8117-c6202373b3eb.JPG)

@rottencandy @csoler  This is also not working.

**Comment by Kumaravinash9** [comment]
@csoler @rottencandy how can i add the new route for changing the identity in retroShare. I need your help . Please guide me .

**Comment by Kumaravinash9** [comment]
@csoler , I am not able to find any file  having name rsidentity.h in RSNewWebUI repo.

**Comment by Kumaravinash9** [comment]
Thanks @csoler , I will check it out.  I am looking forward to participate in GSOC 21  on this organization. Is any format  you decided for the proposal.

**Comment by csoler** [comment]
You need to apply. Given what you already achieved, you have great chances. I suppose your application must contain some milestones for what to achieve. I suggest you send me a draft of what your plans are so that I can validate them, then submit it in the format GSoC expects.

**Comment by Kumaravinash9** [comment]
@csoler it's grate help . If you will share your retro-share id with me  . so that i will able to send you my draft proposal for the review.

**Comment by csoler** [comment]
you're connected to the dev Tor node, so you can send me your draft. No problem with that.

**Comment by Kumaravinash9** [comment]
pardon me @csoler , Actually my pervious  retroshare version was not working . So , i download the new version  that was recommended by @anmo.  That's why my identity has changes . Can you please add my new key to Tor Node.

ABDLrPSwkMxDUm57NC1bYreFAxTHCkJwSRUFPk+2P8R5TaUUQpzn0AEIS3VtYXJBdmmTBgGJqMCmqpIGfNb7daaqBAPIRJM=

**Comment by csoler** [comment]
you know that when you upgrade RS, you do not have to create a new identity everytime?

**Comment by Kumaravinash9** [comment]
@csoler  i donot know about it . How can i retrieve my pervious id

**Comment by Kumaravinash9** [comment]
@csoler i have deleted that directory. From next time , i will do it again.

**Comment by Kumaravinash9** [comment]
@csoler please add my key : 
ABDLrPSwkMxDUm57NC1bYreFAxTHCkJwSRUFPk+2P8R5TaUUQpzn0AEIS3VtYXJBdmmTBgGJqMCmqpIGfNb7daaqBAPIRJM=

**Comment by csoler** [comment]
I did

**Comment by Kumaravinash9** [comment]
Thanks @csoler .

**Comment by Kumaravinash9** [comment]
thanks @csoler , i went through libretroshare/src/retroshare/*.h files and got three function update, create and delete identity.

![createidentity](https://user-images.githubusercontent.com/64456168/113086677-be47da00-91ff-11eb-9415-170571517144.JPG)

**Comment by Kumaravinash9** [comment]
Thanks  a lot @csoler ,i have  fixed the issue .

**Comment by Kumaravinash9** [comment]
@csoler , i have completed  my proposal .  And i really want to get your reviews .

Is this your identity . So i will able to send my proposal  google docs link.

![cyril](https://user-images.githubusercontent.com/64456168/113295041-4e2b7800-9315-11eb-91bf-9e0a62f9bebc.JPG)
