### ISSUE TITLE
 I want to use bootstrap 4 for the implementing of  UI 

### ISSUE THREAD

**Issue by Kumaravinash9** [RetroShare/RSNewWebUI#27]
@csoler  @rottencandy  can i use Bootstrap ?

**Comment by rottencandy** [comment]
@Kumaravinash9 Adding a new UI framework would require non trivial amount of changes to the codebase. Better to discuss with others(in dev forum) the pros and cons before going with it.

**Comment by Kumaravinash9** [comment]
Thanks @rottencandy .I will discuss this dev forum. One more question , is this dev forum avaible on retroshare channel or git hub

**Comment by csoler** [comment]
It's available from the dev Tor nodes. Go to forums, subscribe to the dev forum there, and post.

**Comment by Kumaravinash9** [comment]
Thanks @csoler.

**Comment by Kumaravinash9** [comment]
@csoler  should I make my gsocproposal timeline  weekwise or phase wise

**Comment by csoler** [comment]
your call. Phase-wise is a bare minimum. If you do so, try to also provide a time estimate for the different tasks.
Plz submit it way before the deadline so that we can discuss it before.

**Comment by Kumaravinash9** [comment]
Thanks @csoler . I will complete my proposal in two days.

**Comment by Kumaravinash9** [comment]
> @Kumaravinash9 Adding a new UI framework would require non trivial amount of changes to the codebase. Better to discuss with others(in dev forum) the pros and cons before going with it.

@rottencandy i have drooped this feature request on dev forum

**Comment by zelfroster** [comment]
@rottencandy Can we close this issue now? Since we are probably not going to use Bootstrap.
