### ISSUE TITLE
Home View for webui

### ISSUE THREAD

**Issue by defnax** [RetroShare/RSNewWebUI#35]
Hi,
about feature to add via Short retroshare id a friend and optional via long cert.

* Show retroshare id by default
* Copy Retroshare ID Button
* Share Button 
* Add Friend Button ( opens a popup dialog to paste a retroshare id or Cert )
* Web Help Button

![image](https://user-images.githubusercontent.com/9952056/116746611-0a538d80-a9fd-11eb-8c7d-95d67464ef46.png)

**Comment by Kumaravinash9** [comment]
Hello @defnax , I want to work on this issue

**Comment by Kumaravinash9** [comment]
> Hello @defnax , I want to work on this issue

Once the side navbar PR get merged, I will create this PR.

**Comment by rottencandy** [comment]
I don't see any overlap with navbar PR, so if you like you can work on it in parallel ;)

**Comment by Kumaravinash9** [comment]
ok, then I will create this PR soon.

**Comment by Kumaravinash9** [comment]
Actually, I was busy with my semester examination. That's why I was inactive from few days. Now my examination is over.

**Comment by Kumaravinash9** [comment]
##  @rottencandy  @defnax  I have completed this work. Please let me know if it requires any more changes. 

![UIcheck](https://user-images.githubusercontent.com/64456168/117573946-66529c00-b0f8-11eb-8849-203ce281190c.JPG)

**Comment by Kumaravinash9** [comment]
# AddFriend PopUp
![addFriend](https://user-images.githubusercontent.com/64456168/117574300-1d034c00-b0fa-11eb-995d-1c8a050e29ce.JPG)

**Comment by defnax** [comment]
> ## @rottencandy @defnax I have completed this work. Please let me know if it requires any more changes.
> ![UIcheck](https://user-images.githubusercontent.com/64456168/117573946-66529c00-b0f8-11eb-8849-203ce281190c.JPG)

thx that looks nice

**Comment by defnax** [comment]
> # AddFriend PopUp
> ![addFriend](https://user-images.githubusercontent.com/64456168/117574300-1d034c00-b0fa-11eb-995d-1c8a050e29ce.JPG)

there is needs some rewrite the text
"Do you receive a retroshare id from a friend?"
"Paste Friends retroshare id into box"
we use now retroshare ID, and cert optional... now by default retroshare id in desc/info.

![image](https://user-images.githubusercontent.com/9952056/117704685-6d96aa00-b1cb-11eb-940d-7bf13fb194da.png)

**Comment by defnax** [comment]
but i doesnt tested if the functions for copy cert or retroshare id works properly, 
need to look later on it

**Comment by zelfroster** [comment]
Hello, 

I spotted some UI issues which can be fixed.

- The Retroshare ID is a textarea, and it is resizable, which could look weird when tinkered with.
![1678253011_Mar08_10:53:31](https://user-images.githubusercontent.com/93514460/223938290-4fb95a8d-8409-406f-a548-8775540c6c56.png)

- Copy Button and Open Web Help button should show a cursor pointer on hover.
![1678335893_Mar09_09:54:53](https://user-images.githubusercontent.com/93514460/223938387-73564a83-69e5-4a4b-b04c-e64b02a3150f.png)
![1678335903_Mar09_09:55:03](https://user-images.githubusercontent.com/93514460/223938432-938c7f99-1b96-4579-aaa2-363003fb84f7.png)

- The Add Friend popup should have Files upload and input fields separated for clear understanding.
![1678306509_Mar09_01:45:09](https://user-images.githubusercontent.com/93514460/223938684-8876ee6f-2c5f-4101-94d0-f9a15324c17f.png)

- The Popups are not correctly center aligned with the respective viewport size.
![FireShot Capture 027 - RetroShare - 127 0 0 1](https://user-images.githubusercontent.com/93514460/223940592-8c9a6c9f-97eb-4fd0-94a6-9508381a3cc0.png)
![FireShot Capture 027 - RetroShare - 127 0 0 1](https://user-images.githubusercontent.com/93514460/223941369-a8d932a4-13a3-4a98-a20c-3fe4052534ee.png)

**Comment by zelfroster** [comment]
Please suggest some more issues if any.

And assign me so I can work on it.

Tagging @csoler for review.

**Comment by defnax** [comment]
there are lots issues webui is not realy useable.
example mail page or boards page and lots of ther things

**Comment by zelfroster** [comment]
> there are lots issues webui is not realy useable. example mail page or boards page and lots of ther things

Yes, My initial thought was to refactor the whole UI. Must take time, But I am willing to do it.
The code is old and there are so many hacky stuff. Needs an update.

**Comment by defnax** [comment]
> 

i replied her some issues on mail composer
https://github.com/RetroShare/RSNewWebUI/pull/59

example this not useable
![image](https://user-images.githubusercontent.com/9952056/224400970-cf5e3827-26d7-4d83-be4f-727ad8a64148.png)

painted then this last year
![image](https://user-images.githubusercontent.com/9952056/224401025-86cdf0cf-1a4f-4886-a237-228a2d6d8772.png)


maybe i wanted say it needs to looks easy and userfriendly like a mail composer looks more nice :)
example the selection box for find a contact you will need lots time to find your contact to selected :D

**Comment by zelfroster** [comment]
I agree.
God, this needs a lot of work.
Give me strength 😂 

I will start working and keep you updated.
