### ISSUE TITLE
UI design for the Mail Tab

### ISSUE THREAD

**Issue by Kumaravinash9** [RetroShare/RSNewWebUI#39]
**Added the UI design for the Mail tab that was mentioned by @defanx in `side navbar ` PR.**

![](https://user-images.githubusercontent.com/9952056/117193626-63e3ff80-ade3-11eb-932f-1a790df41c6b.png)

**Comment by defnax** [comment]
the design idea is more from qt ui mail similiar like thunderbirds mail ui
![image](https://user-images.githubusercontent.com/9952056/117712826-1c8bb380-b1d5-11eb-911f-d6281d187b78.png)

![image](https://user-images.githubusercontent.com/9952056/117713305-c66b4000-b1d5-11eb-8ee8-2a4355a70a76.png)

**Comment by Sukhamjot-Singh** [comment]
![ss](https://user-images.githubusercontent.com/56192331/152301709-e4ed1eab-7f82-444d-a15d-67c0697f20c7.png)

I have added the compose button separately and have made a dummy component for the same named 'mail_compose.js'
My questions

1. Should I include it in the sidebar like the rest of the options(inbox, draft etc)?
2. If I do it separately(like in the screenshot), how do I route the button to show that component along the sidebar?(I am new to mithril.)
3.

**Comment by defnax** [comment]
i has no knowledge with javascript or with mithril,
the mail composer needs looks like composer from the qt ui or like tunderbirds composer

**Comment by defnax** [comment]
the side bar ist not needed in composer ivew, when you open the Retroshare Mail composer you will see it how it needs to look

**Comment by rottencandy** [comment]
I think it's good to have the compose button outside of the sidebar like you have done.
And like defnax said there won't be a sidebar for the compose page, so you can create a new route and a page for it.

**Comment by defnax** [comment]
here the basic todos for mail composer and mail page:

Mail windows missed things:

- From (Column) for Inbox
- To (Column) for outbox, sent
- Trash box
- System Box
- Spam Box
- Attachments box
- Tags list box
- reply/replyall, forward, delete buttons

you will see on the rs mail window the features which are missed in the webui

**Comment by defnax** [comment]
@G10h4ck @Kumaravinash9

**Comment by rottencandy** [comment]
You can find all api endpoints here https://github.com/RetroShare/libretroshare/tree/master/src/jsonapi

**Comment by defnax** [comment]
i dont know iverything is done look here:
https://github.com/RetroShare/libretroshare/blob/a7a430008b76e53727598c4d13106e7ce95221d7/src/retroshare/rsmsgs.h#L588

**Comment by Sukhamjot-Singh** [comment]
Hello @defnax , @rottencandy 
I would love if you could help me review my GSoC proposal for webUI

**Comment by defnax** [comment]
@Sukhamjot-Singh  you has a own proposal? for webui? i doesnt saw it

**Comment by csoler** [comment]
@Sukhamjot-Singh I can do that. Can you send it by email? Or on retroshare.

**Comment by Sukhamjot-Singh** [comment]
> @Sukhamjot-Singh I can do that. Can you send it by email? Or on retroshare.

Yes I already did that by email.

**Comment by G10h4ck** [comment]
The JSON API already expose anything needed for profile creation and login, and I think it is a priority to implement that in webui, this way retroshare-service can be used stanfalone without trickeries, about mail tab I think we should give priority to basic functions, like mail reading, sending and maybe folder, I would completely ignore tags, stars and all the unnecessary things we have in retroshare-gui

**Comment by defnax** [comment]
some nice design idea for mail page (low prio) @zelfroster 
![image](https://user-images.githubusercontent.com/9952056/224742012-4ed3f705-164d-4f7e-8846-e75c6ca252ea.png)

https://vadosware.io/post/mithril-systemjs-and-rollup-getting-started-guide/

**Comment by defnax** [comment]
this issues is not fixed yet it adds on every recipient a new line, needs to be fixed:
![image](https://user-images.githubusercontent.com/9952056/224802688-cbc7f983-4f7a-4545-9025-49738b6d0e07.png)

**Comment by zelfroster** [comment]
> this issue is not fixed yet it adds on every recipient a new line, needs to be fixed: ![image](https://user-images.githubusercontent.com/9952056/224802688-cbc7f983-4f7a-4545-9025-49738b6d0e07.png)

I fixed this issue by adding a button to `show more` or `show less`

![FireShot Capture 048 - RetroShare - 127 0 0 1](https://user-images.githubusercontent.com/93514460/224964561-58c01858-1ce7-4f70-baf7-6a1784203fdd.png)
![FireShot Capture 049 - RetroShare - 127 0 0 1](https://user-images.githubusercontent.com/93514460/224964581-ae71fc14-a147-4464-a897-dc60e21a060a.png)

Is it good or should I change something.

**Comment by Sukhamjot-Singh** [comment]
> > this issue is not fixed yet it adds on every recipient a new line, needs to be fixed: ![image](https://user-images.githubusercontent.com/9952056/224802688-cbc7f983-4f7a-4545-9025-49738b6d0e07.png)
> 
> I fixed this issue by adding a button to `show more` or `show less`
> 
> ![FireShot Capture 048 - RetroShare - 127 0 0 1](https://user-images.githubusercontent.com/93514460/224964561-58c01858-1ce7-4f70-baf7-6a1784203fdd.png) ![FireShot Capture 049 - RetroShare - 127 0 0 1](https://user-images.githubusercontent.com/93514460/224964581-ae71fc14-a147-4464-a897-dc60e21a060a.png)
> 
> Is it good or should I change something.

Looks great!

**Comment by defnax** [comment]
thats good for now, but after "To: "need one empty space.
anytime later the mail recipients needs to be higlighted with linking, not sure if its doable yet, example like how on rs qt ui "identityname@id"

**Comment by zelfroster** [comment]
> thats good for now, but after "To: "need one empty space. anytime later the mail recipients needs to be higlighted with linking, not sure if its doable yet, example like how on rs qt ui "identityname@id"

Let me see if It can be done. And don't worry about the Css stuff. I have actually applied some sane defaults and will be fixing up UI later.

**Comment by zelfroster** [comment]
> > thats good for now, but after "To: "need one empty space. anytime later the mail recipients needs to be higlighted with linking, not sure if its doable yet, example like how on rs qt ui "identityname@id"
> 
> Let me see if It can be done. And don't worry about the Css(spacing or design) stuff. I have actually applied some sane defaults and will be fixing up UI later.

**Comment by defnax** [comment]
design stuff not importend yet, thanks for help

**Comment by zelfroster** [comment]
Hey maintainers, I am trying my best to do things as quick as possible.
But for any reason, If you feel my pace is slow or anything weird about me, Please tell me 😅.

Btw @csoler Should I start writing proposal for GSOC?

**Comment by Sukhamjot-Singh** [comment]
As long as you show some progress in the PR and understanding of APIs, I think you will do fine. Rest is on @csoler  to decide ;).
Please start writing the proposal and if you need help, reach out to me at sukhamjot2001@gmail.com

**Comment by csoler** [comment]
yes definitely. It's probably better if we discuss your working plan before you submit it.

**Comment by zelfroster** [comment]
> yes definitely. It's probably better if we discuss your working plan before you submit it.

Thanks to both of you 😁, will start writing the proposal tomorrow.
And will share and discuss here.

**Comment by zelfroster** [comment]
**fixed**
* When mail contains no Author/from, the date will be added to the wrong field
![1678974762_Mar16_19:22:42](https://user-images.githubusercontent.com/93514460/225639474-20c2f77d-3a29-42a9-921f-1ec00aeb8b88.png)
![1678974789_Mar16_19:23:09](https://user-images.githubusercontent.com/93514460/225639506-b533c36a-afa9-4489-bc26-a543486e042f.png)

**Comment by defnax** [comment]
nice thx

**Comment by zelfroster** [comment]
> nice thx

For the sort by date for mails, should We have both newest and oldest at top feature or just only one?

**Comment by defnax** [comment]
@Kumaravinash9 @rottencandy  please close this , i create a new issue for it
