### ISSUE TITLE
WeBUI - Mail, Network, Chat, People, Files

### ISSUE THREAD

**Issue by defnax** [RetroShare/RSNewWebUI#43]
Hi 
thank you @Kumaravinash9 & @gunjan543 for helping us on the webui.

At the moment there are some todos 

- #39 **Mail**
- #42 **Chat rooms**
- #36 **Network View**
- #44 **Files View**
- #60 
* Private Chat (with Node), Distant Chat (with Contacts/People)
* People Ui ( better design like the qt ui)

we need a useable 1:1 chats too 
* Show **private Chat** with Nodes in **Network -> Chat Conversation/History**
* Show **distant Chat** with Contacts/People **People ->Conversations List -> Conversation/History**

Idea for Network Node Chat, Contacts/People Distant Chat and Chat Rooms, would be great we have the same design structure
when possible.

**Comment by Kumaravinash9** [comment]
Thanks @defnax . Will working here as a GSOC intern this year

**Comment by defnax** [comment]
There is more todo, but its best that importend communication part will be first useable before going to adopt new pages :)

**Comment by csoler** [comment]
you seem to also forget file transfer. For now it's not possible to see what files are shared, what's the progress of downloads, etc.

**Comment by defnax** [comment]
> you seem to also forget file transfer. For now it's not possible to see what files are shared, what's the progress of downloads, etc.

yes you are right thats importend too, i forget it

**Comment by Sukhamjot-Singh** [comment]
Are these issues still open?
If not, can someone guide me to some issues or fixes I can work on?
Thanks

**Comment by defnax** [comment]
> Are these issues still open? If not, can someone guide me to some issues or fixes I can work on? Thanks

yes all still open, and we dont know when @Kumaravinash9 comes back for help.
The webui still not ready or useable everything not done or finished.

**Comment by Sukhamjot-Singh** [comment]
I have installed everything and built the webui. But what id password do I have to enter in the webUI
It is showing me the error _Retroshare-jsonapi not available.
Please fix host and/or port._

**Comment by Sukhamjot-Singh** [comment]
> 

I have Enabled the JSON API server in the retroshare app but what login password do I have to enter.?
Please help so I can contribute further

**Comment by csoler** [comment]
you need to add a token in the WebUI tab of the preferences of retroshare-gui. 
The token should be "webui:passwd" where you replace passwd by your password.

**Comment by Sukhamjot-Singh** [comment]
![image](https://user-images.githubusercontent.com/56192331/150564854-2b483d06-99f4-4de9-8921-2a9ad13ee688.png)
![image](https://user-images.githubusercontent.com/56192331/150564906-c03b9ee3-1131-4959-930b-911d7d01baf5.png)

@csoler Thanks for the quick reply but I am still facing the error

**Comment by rottencandy** [comment]
@Sukhamjot-Singh what error do you see in the browser console?

**Comment by csoler** [comment]
I think the problem is that you compiled with rs_jsonapi but not with rs_webui. Both are needed for webUI to work. What happens now is that webUI JS part is trying to talk to RS but RS does not respond because it doesn't expect anything on localhost/webui/index.html

**Comment by Kumaravinash9** [comment]
Which os are you using @Sukhamjot-Singh ?

**Comment by Kumaravinash9** [comment]
In windows there are some problem with compilation ? Last year I also faced issues.

**Comment by hunbernd** [comment]
There is currently a problem due to the recent changes, but it is easy to fix:
Copy these files from **libretroshare\src\jsonapi\\** to **jsonapi-generator\src\\**
* async-method-wrapper-template.cpp.tmpl
* method-wrapper-template.cpp.tmpl
* jsonapi-generator-doxygen.conf

Then rebuild RS.
If you use the msys2 scripts:
build 64 release webui
pack 64 release webui

**Comment by Sukhamjot-Singh** [comment]
> @Sukhamjot-Singh what error do you see in the browser console?

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:9092/rsEvents/registerEventsHandler. (Reason: CORS request did not succeed). Status code: (null).

**Comment by Sukhamjot-Singh** [comment]
> Which os are you using @Sukhamjot-Singh ?

ubuntu -linux

**Comment by Sukhamjot-Singh** [comment]
> I think the problem is that you compiled with rs_jsonapi but not with rs_webui. Both are needed for webUI to work. What happens now is that webUI JS part is trying to talk to RS but RS does not respond because it doesn't expect anything on localhost/webui/index.html

I did not compile with anything, it was mentioned in the docs if the retroshare app is showing JSON API option you dont need to compile with anything.
I just built the file.

**Comment by Sukhamjot-Singh** [comment]
It has compiled!
I built once again using qmake .
Thank you @csoler  @Kumaravinash9  @rottencandy @hunbernd . Looking to forward to contributing.
Also is freifunk/Retroshare participating in GSOC?

**Comment by csoler** [comment]
yes definitely. You're very welcome to join and make some contributions to RSWebUI. That will give you a very good chance to get a GSoC slot provided that Google actually gives slots to Retroshare this year.

**Comment by csoler** [comment]
I fixed the README.md of RSNewWebUI as it was really outdated.

**Comment by Sukhamjot-Singh** [comment]
I have looked at the code now. i can solve some issues.
Can anyone tell me how can I add friends and chat channels(dummy or real) so that I can work with the UI

**Comment by csoler** [comment]
In the Web interface, just click on "add friend" in the main page, and paste your friend's certificate. On the friend's side, add your own certificate.

**Comment by Sukhamjot-Singh** [comment]
> > I have looked at the code now. i can solve some issues. Can anyone tell me how can I add friends and chat channels(dummy or real) so that I can work with the UI
> 
> best is first add new friends over the retroshare qt ui to get some friends, on rs webui is not all 100% working very well you can send me your cert we can add you to the dev network, then it will be easier test and develope on it


ABBuYBdPh+AoCCP4sE5G5IYDAxSwby53Yx9Cxb7R4CmBNJx+cZGMMAENc3VraGFtam90MjAwMZMGhB2owI3Dkgaw0CQxjcMEA3Na
Yg==

**Comment by defnax** [comment]
what time you are online? send me your cert via email look on my profile.
im often 7 to 10pm (UTC+1) online

**Comment by Sukhamjot-Singh** [comment]
> 

I am online 11am - 4pm(UTC) online 
Okay I will mail you

**Comment by defnax** [comment]
> > 
> 
> I am online 11am - 4pm(UTC) online Okay I will mail you

when you check your mail?

**Comment by defnax** [comment]
@Sukhamjot-Singh the basic todos are listed here on top

**Comment by Sukhamjot-Singh** [comment]
Hello everyone, I am setting up my environment on WSL.
can someone add my cert.

CQEGAcGexsBNBGJTAY0BCADcff36Tn/Di+4hiim9qys2mqXLRIkxnhBxGXplcRta
THPQpOH+UZJtf1C2ZO4yLhF6HOIiOFHQ/l6oLNgxMMMkmdTmtclGwbWzgltDBvI5
MkFoIS9Vbg/EOssFcoVYoCR/9QHKoxybTbfGoXYmI6/+KG+vPMPD26VjAlPQtAHr
6PTZ0xjd2PfEmaGtEVTUR+r9EWe77l7QzHHOKfuGrGXeYI/DEUSul2kcnF2Deqv1
qtZb3LRON29jjveBqVLt4oBLuJYFaqvI66+0bVZNvrfzM32AB9+1r7BAXUOGYjKX
ph2GkDthM8Lkbgs215BlMUIn0jsB8iEGU9Yrk9SY2a+1ABEBAAHNKnN1a2hhbWpv
dDIwMDEgKEdlbmVyYXRlZCBieSBSZXRyb1NoYXJlKSA8PsLAXwQTAQIAEwUCYlMB
jQkQikRxNRSPKHECGQEAAMFCCACLDxoXM5l6/RZT2xUNzSDb9e6j6vgmhyBv75qn
IQ8dMeALeoL6X38x4AbspPW8CwNGw0aHMmQH//1rvFxlWit1Bt/DdOZrohk4yiS2
KXLpt1GaPWQN31yCqH+Las++iZx29qoKLp2TuA01BsxLsXip8s5gOyjMsRs+LlJg
zJe+Cf1DisOVLLFRrcJe4djP1Rwph1+PXzWi/MBgg2Lfq21xQ98mfPSBGrjQmHlj
TuV0S4A931rlxQ3MXQwVaoWVTL56JpxCBX8juyfaKBGfQwmXC+pm111c4b0ePFiB
xAIh77SSjCgS2HQzAdJjGCBvuUpOhvqA/UUgD6besQQ76/QFAgbAqB0qhIgDBsCo
HYWEiAQABgtNeSBjb21wdXRlcgUQqpdVngnuD8PHKNrbXSV3RQcDohwG

@defnax @csoler @G10h4ck 

Also there is some CORS error I face when I log into my web interface but is fixed when I repeatedly login.

**Comment by G10h4ck** [comment]
I suggests you exchange keys with this 24/7 nodes http://pool.elrepo.io/

Also @csoler manages a node specifically for development purposes

**Comment by defnax** [comment]
@Sukhamjot-Singh send you a mail
