### ISSUE TITLE
Bug: FIleSize> 2gb throws  exception

### ISSUE THREAD

**Issue by Kumaravinash9** [RetroShare/RSNewWebUI#47]
Issue is coming  when we try to parse the file size having int64 size  using IntParse. We can use the `BigNumber`  when file size is of 64 bit size.
Here is the solution of this  Bug :
http://jsfromhell.com/classes/bignumber

**Comment by Kumaravinash9** [comment]
@cslor @rottencandy.

**Comment by Kumaravinash9** [comment]
> or @rottencandy.

**Comment by rottencandy** [comment]
Fixed in #48 
Thanks @Kumaravinash9 !

**Comment by rottencandy** [comment]
Reopening since #48 did not fix it, the filesize still shows incorrectly.

**Comment by Kumaravinash9** [comment]
> Reopening since #48 did not fix it, the filesize still shows incorrectly.

But I replaced the `int64` with `xstr64`.

**Comment by rottencandy** [comment]
It still seems to report the size incorrectly, not sure why.
I tried to manually serialize the data: https://github.com/RetroShare/RSNewWebUI/pull/49
