### ISSUE TITLE
Api for Boards doesnt works

### ISSUE THREAD

**Issue by defnax** [RetroShare/RSNewWebUI#53]
Hi, i have tested with curl the api for boards but it doesnt works, for channels/forums working perfect.
or someone forget to enable/add api feature for boards? 

@G10h4ck @zeners @csoler @Kumaravinash9 @Sukhamjot-Singh @sehraf  

![image](https://user-images.githubusercontent.com/9952056/171931848-7ea84d96-3447-4564-9608-fff44d384fbd.png)

**Comment by defnax** [comment]
when i add this to rsposted.h class then the api will work?
![image](https://user-images.githubusercontent.com/9952056/171994013-f929a56f-cb0a-41bc-8d69-6490b271b1f7.png)

**Comment by sehraf** [comment]
That _should_ do the trick.

---
( Since the global pointer **is** already exposed )
```c++
/**
 * Pointer to global instance of RsGxsChannels service implementation
 * @jsonapi{development}
 */
extern RsPosted* rsPosted;
```

**Comment by defnax** [comment]
hi maybe you can check with my pr is right? maybe not complete or someone do the rest?

https://github.com/RetroShare/libretroshare/pull/31
