### ISSUE TITLE
use sidebar for webui

### ISSUE THREAD

**Issue by defnax** [RetroShare/RSNewWebUI#6]
hi,

thx for nice webui great work .

but i prefer we need to use the same method like other social  platforms like tribler, zeronet,....
top Bar is mostly used for search, menu, actions, notify count, settings or account stuff
but for page navigation is best to use a left side SideBar.
![image](https://user-images.githubusercontent.com/9952056/71289769-3fae8c80-236e-11ea-8e87-9231fef9300f.png)

https://forum.tribler.org/t/tribler-web-interface/4233

**Comment by rottencandy** [comment]
Hi @defnax,

Thanks for the suggestion.
Makes sense to have a sidebar for the tabs, instead of a top bar.

Do you have any suggestion on how the layout should look for tabs that already have a sidebar(for example, the config tab)?

**Comment by defnax** [comment]
> Do you have any suggestion on how the layout should look for tabs that already have a sidebar(for example, the config tab)?

i think alternative is main sidebar black background and for config tab white background and other pages with sidebars
i use since few years on qt gui with sidebar its more comfortable the navigation.

![image](https://user-images.githubusercontent.com/9952056/71309899-a8991180-240d-11ea-8dff-933f281d1792.png)
![image](https://user-images.githubusercontent.com/9952056/71309931-04639a80-240e-11ea-883d-ab33657fc3be.png)
