### ISSUE TITLE
Improve Sidebar UI

### ISSUE THREAD

**Issue by zelfroster** [RetroShare/RSNewWebUI#62]
I am thinking of making the sidebar a bit modern.

So, I just wanted to ask, 

Is it Okay if I tweak the color scheme a bit? Or Should I go with the existing ones.

**Comment by zelfroster** [comment]
Does this Sidebar look good?
Please suggest changes if any. I am new here, and I really want to contribute to this project, that's why I am solving some basic issues first.

![1678393334_Mar10_01:52:14](https://user-images.githubusercontent.com/93514460/224146925-e5d9f0dd-4d81-465d-90f1-a87d8ee4d496.png)

**Comment by zelfroster** [comment]
Added the Logo and Title in the Navbar.
![1678400987_Mar10_03:59:47](https://user-images.githubusercontent.com/93514460/224174954-b9fcd2ce-d675-46f1-a5b2-9f8f4f8d510d.png)

**Comment by zelfroster** [comment]
I will send this PR once the #61 gets merged. :)
Someone, please review that and check this 😓

**Comment by defnax** [comment]
@csoler @rottencandy
