### ISSUE TITLE
File Search : Response from the `turtleSearchRequest` is not correctly formatted

### ISSUE THREAD

**Issue by zelfroster** [RetroShare/RSNewWebUI#73]
The response from the `turtleSearchRequest` is not correctly formatted as JSON, so that's why `handleDeserialize` throws error when parsing in `rswebui.js`.
![1682775057_Apr29_19:00:57](https://user-images.githubusercontent.com/93514460/235310073-6d0e57dd-b64d-4a8c-968b-379ab6be6ff5.png)

So, The correct format for response should be like this.
An object which will have its first item as a `retval: <boolean>`. And the second item which will be an array of all the result files `"results": [{},{}]`
```json
{
  "retval": true,
  "results": [{ "fSize": {}, "fHash": "", "fName": "", "fWeight": 0.0, "fSnippet": ""}, { }, { }]
}
```

The real response might look something like [this](https://pastebin.com/HWZeeg8B). 

And after formatting, It will look something like this.
![1682785511_Apr29_21:55:11](https://user-images.githubusercontent.com/93514460/235313131-40b9b399-6c47-4dfc-b6b5-9670e226783a.png)

**Comment by zelfroster** [comment]
@csoler Have a look at it.

**Comment by rottencandy** [comment]
What format are you getting currently?

Turtle search request returns as a stream so I don't think all the data in results list will be available immediately.

**Comment by zelfroster** [comment]
> What format are you getting currently?
> 
> Turtle search request returns as a stream so I don't think all the data in results list will be available immediately.

Yes, I actually didn't know that It was coming as a stream, and Cyril told me about that when we discussed.
So, currently, I am able to get the data as chunks of stream as soon as they are fetched from the server.
![1683035779_May02_19:26:19](https://user-images.githubusercontent.com/93514460/235688287-14459c4f-43ac-4c0c-ad8b-137a6078c050.png)

But, Since TurtleSearchRequest doesn't send an end of stream marker, there is no way to know when the stream ends. So, I am thinking of setting a time duration using setTimeout to manually stop the connection.
![1683035865_May02_19:27:45](https://user-images.githubusercontent.com/93514460/235690748-0ede03ac-ac5f-4ca8-b1bb-addd1e7c1d78.png)
![1683035884_May02_19:28:04](https://user-images.githubusercontent.com/93514460/235690894-36de8d09-9ce3-4d30-a31e-01bdebf8826f.png)
![1683035897_May02_19:28:17](https://user-images.githubusercontent.com/93514460/235690915-2b01b796-9915-4a45-8ac9-e1793eccc5ac.png)
![1683036439_May02_19:37:19](https://user-images.githubusercontent.com/93514460/235691179-db3290e0-a5b5-4b76-8f74-3a2641296584.png)

Please suggest some better ways, I could only think of this by doing some research.

**Comment by csoler** [comment]
Setting a timeout is ok. I do not think that there is another way because RS keeps accepting results coming for each specific search request. I'm not sure how JS works, but ideally you should keep a list of search request IDs and fill them with incoming results (suppose for instance that you search twice, then you will receive results for both searches alternatively), and update them on display. When the search is "closed" (from your JS interface) then just ignore the related incoming results. Is that possible in JS?

**Comment by zelfroster** [comment]
> (suppose for instance that you search twice, then you will receive results for both searches alternatively), and update them on display. When the search is "closed" (from your JS interface) then just ignore the related incoming results. Is that possible in JS?

Yes, As soon as someone creates a new search request, the latest search results will only be shown. And If we move to a different page, then we can use `onunload` method to abort the search request.

> also, one may issue a search from the Qt UI, so the webUI will also receive results for some unknown searches. I suppose that you can afford to ignore these.

I have tested it, and Qt UI results should not be shown in JS request.

**Comment by csoler** [comment]
> Yes, As soon as someone creates a new search request, the latest search results will only be shown. And If we move to a different page, then we can use `onunload` method to abort the ongoing search request.

That is not what I was saying: when you change pages (in other words, look at the results of a different search) you should keep the previous search active, since more results are likely to come. When you *close* that page however, you can remove the search id from the list and ignore additional results that will come for this search.

**Comment by zelfroster** [comment]
> > Yes, As soon as someone creates a new search request, the latest search results will only be shown. And If we move to a different page, then we can use `onunload` method to abort the ongoing search request.
> 
> That is not what I was saying: when you change pages (in other words, look at the results of a different search) you should keep the previous search active, since more results are likely to come. When you _close_ that page however, you can remove the search id from the list and ignore additional results that will come for this search.

Ohh, So If I understood correctly, You are saying that I should keep the results of all the search requests stored, So that It can be shown just like the Qt UI.
Yes, I think It can be done.

**Comment by csoler** [comment]
each search request is unique since it is represented internally by its 32bits ID. The search strings may be the same for two search requests, but these requests should be understood to be different since they have different IDs.

**Comment by zelfroster** [comment]
> each search request is unique since it is represented internally by its 32bits ID. The search strings may be the same for two search requests, but these requests should be understood to be different since they have different IDs.

Then, I would have to manually give them an ID. Either way, It can be done.

**Comment by csoler** [comment]
Normally the ID should be returned by turtleSearchRequest(). It is the only way you can fit further results with that request.

**Comment by zelfroster** [comment]
> Normally the ID should be returned by turtleSearchRequest(). It is the only way you can fit further results with that request. [edit] actually it doesn't. I will change the function tonight so that it returns an ID instead of a bool, as other turtleSearch methods do. I'll keep you posted.

Ohh, Thanks for this. 👍🏼
